//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practical_task_18_Animals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalsDBContainer : DbContext
    {
        public AnimalsDBContainer()
            : base("name=AnimalsDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birds> BirdsSet { get; set; }
        public virtual DbSet<Amphibians> AmphibiansSet { get; set; }
        public virtual DbSet<Mammals> MammalsSet { get; set; }
    }
}
