//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practical_task_18_Animals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mammals
    {
        public int Id { get; set; }
        public string Detachment { get; set; }
        public string Family { get; set; }
        public string ViweAnimal { get; set; }
    }
}
